version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '10001:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cinema-db
